

POST https://expensetrackerbytim.herokuapp.com/user
Content-Type: application/json

{
    "name": "user post",
    "password": "user password"
}

###

GET http://localhost:3000/60f0d1616a8fe40d8aaad754

###

POST http://localhost:3000/expensetracker/addtransaction/60f440e29526d3001566cffa
Content-Type: application/json

{
    "transaction": {
        "id": 175600399,
        "transactionAmount": "500",
        "transactionType": "working"
    }
}

### 

POST http://localhost:3000/60f0d1616a8fe40d8aaad754
Content-Type: application/json

{
    "username": "updated username",
    "password": "updated password"
}

### 

DELETE  http://localhost:3000/60f0e2ae8d06b80ff370c17b

###

GET http://localhost:3000/expensetracker/allusers

###

GET https://expensetrackerbytim.herokuapp.com/expensetracker/transactions/60f307c36c574f00150b4919

###

POST http://localhost:3000/expensetracker/deletetransaction/60f440e29526d3001566cffa
Content-Type: application/json

{
    "transaction": {
        "id": 175600399,
        "transactionAmount": "500",
        "transactionType": "working"
    }
}